version: "3"
services:
  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_DATABASE: smart_home_sync
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: ss1235789
    volumes:
      - /mysql:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - smart_home_sync
    restart: always

  springboot:
    shm_size: '30gb'
    build: ./
    image: smart-home-sync
    container_name: smart-home-sync
    volumes:
      - /springboot:/upfiles
    networks:
      - smart_home_sync
    ports:
      - 9999:9999
    depends_on:
      - mysql


networks:
  smart_home_sync:
    driver: bridge