server:
  port: 9999

# DataBase Settings
spring:
  datasource:
    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000
      connection-init-sql: SELECT 1
      validation-timeout: 2000
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smart_home_sync?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: root
    password: ss1235789
    type: org.apache.commons.dbcp2.BasicDataSource

# MyBatis Setting
mybatis:
  mapper-locations: mapper/**/*.xml
  type-aliases-package: com.cjw.smarthomesync.**.domain


# Jwt Setting
jwt:
  secret: PRIVATE_KEY
  token-validity-in-minutes: 10000
  refresh-validity-in-minutes: 1000000

# Swagger Setting
# Swagger springdoc-ui configuration
springdoc:
  packages-to-scan: com.cjw.smarthomesync
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path : smarthomesync-api.html # localhost:8080/~~-api.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
    cache:
      disabled: true
